# Spring??
spring:
  datasource:
    host: localhost
    url: jdbc:mysql://${spring.datasource.host}:3306/foodsearch?useUnicode=true&characterEncoding=utf8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=JST&connectionTimeZone=SERVER
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Sugamon121028
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: foodsearch
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 1200000


# MyBatis??
mybatis:
  mapper-locations: classpath:com/yuksuga/foodsearchapi/repository/mybatis/*.xml


# ????(SQL???????????)
logging.level:
  com.yuksuga.foodsearchapi.repository: debug
  org.springframework.jdbc.datasource.DataSourceTransactionManager: debug


# ?????SpringBoot???????????????????Actuator????
management:
  endpoints:
    web:
      exposure:
        include: shutdown, health
  endpoint:
    shutdown:
      enabled: true
